### ISSUE TITLE
Enable light when state off

### ISSUE THREAD

**Issue by fank** [cryzed/Amby#1]
When you start the app it only shows:
```
Exception occurred while controlling light #5: parameter, xy, is not modifiable. Device is set to off.
```

Until i set light to on, manual.
It would be nice if there is an option to enable the light, when off, on startup.
And maybe disable if stopped, should depend on the initial state on startup.

**Comment by cryzed** [comment]
Hey, after updating your installation (`pip install https://github.com/cryzed/Amby/archive/master.zip --upgrade`), you should now be able to use `--enable/-e` and `--restore-state/-r` to do what you want. Let me know if it works for you.

**Comment by fank** [comment]
It works :D thanks
