### ISSUE TITLE
Could not find a version that satisfies the requirement PyQt5 

### ISSUE THREAD

**Issue by RogueVeggie** [cryzed/Amby#3]
Could not find a version that satisfies the requirement PyQt5 (from Amby==1.3) (from versions: )
No matching distribution found for PyQt5 (from Amby==1.3)

Running latest version of lubuntu.

**Hi, I've installed all the prerequisite installs to include pyqt5 but I'm getting the above error when trying to install Amby...

 Not sure if you're still working on this tool but I hope you're available for troubleshooting.**

**Comment by cryzed** [comment]
Hello! Sorry for getting back so late to you. How are you trying to install Amby? Creating a virtualenv as instructed in the README and then `pip install`-ing it, should just work.

The only reason for that error I can imagine is either that you are running a 32bit version of Ubuntu, for which no binary [wheels](https://pypi.org/project/PyQt5/#files) exist on PyPi, or you are using Python 2 to install Amby, for which no PyQt5 release exists. Use a version of Python 3.5+ at least to use Amby.

**Comment by RogueVeggie** [comment]
Yup I had the 32 bit running. Got it operating on the 64 version of lubuntu. Now that it's operational I see "(python3:11479): dbind-WARNING **: 22:15:24.058: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
QApplication: invalid style override passed, ignoring it." with the last line repeating constantly. Is that normal?

**Comment by cryzed** [comment]
I think the first relates to a missing DBUS-service(?) that Qt might be trying to make use of/query if it exists, the latter is related to your Qt5 theme settings. You can ignore both safely, they shouldn't stop Amby from working.

Personally I configured Amby to autostart through Plasma and never see any of this output. Hope everything else works well for you :+1: !
