### ISSUE TITLE
Gtk-Message: 22:29:57.260: Failed to load module "unity-gtk-module"

### ISSUE THREAD

**Issue by jcklpe** [cryzed/Amby#4]
```
┌─ ~                                                                                                                          
└─➤ amby 192.168.1.140 1 -e
Running, press Ctrl+C to stop Amby.
Gtk-Message: 22:29:57.260: Failed to load module "unity-gtk-module"
Gtk-Message: 22:29:57.262: Failed to load module "unity-gtk-module"
```

A couple of other things. The instructions for installation says that it needs to be installed as user but pip wouldn't let me install as user. I had to install as root. Your instructions seem to indicate that this has happened before but your instructions don't explain how to get around that problem. Simply repeating the commands does not work, so I ended up installing as root because that seemed the only way forward.

**Comment by cryzed** [comment]
Did you not use the `--user` flag when installing it with `pip`? Or alternatively created a Python virtual environment? Now that you installed it as root, it will most likely work without issues, but you have untracked files in your system that might bite you later.

The `Gtk-Message` lines are of no importance, Amby should work.

**Comment by jcklpe** [comment]
@cryzed  Sorry I'm still very new to development, and I wasn't really sure what you mean by the user flag. Wouldn't that just allow me to specify the user to act under? But also isn't that specified by me running the command? I'm not familiar with running with the user flag except in the case in which I need to manually do a CLI command as my www-data user for making settings adjustments on my personal cloud website. 

Also do you know an easy way for me to look up what the numbers for my lights are? Is that perhaps in the Hue app at all?


Thank you for the help !

**Comment by cryzed** [comment]
By flag I mean a word prefixed by either `--` or `-`. These flags are usually passed to commands/programs. In the case I described above `--user` is a flag (or "signal") passed to the Python package manager `pip` which instructs it to install the package in a user-accessible directory. You can infer that the flags of the same names might have different meanings to different programs.

For me, if I navigate to "Rooms & zones" in the official Hue app, my lights are named "Extended color light n" where n is a number (unless renamed) -- this should be the index you want to use. I am pretty sure it's just an increasing integer.

I'll close this issue for now, because it seems like Amby is working and you were just confused about the installation instructions.

**Comment by jcklpe** [comment]
@cryzed Thanks :) I managed to get all my lights figured out via trial and error because I had already renamed all of them. If you know a way that I can look the numbers up otherwise though let me know please, just because I'm trying to better educate myself on this subject. 


Also I know what flags are. But my understanding is the that the user flag is auto passed as whatever account you're logged into a computer as. I'm more just asking this for my own education.  Why does an explicitly --user flag need to be passed for installation? I'm unfamilar with python installs but isn't that stuff passed in automatically unless you're trying to install something as a user that you're not currently logged in under? (such as when I run stuff as my www-data user)?

**Comment by cryzed** [comment]
I don't know of a different way, although the Phillips Hue API might provide other options (which I never bothered to implement).

> But my understanding is the that the user flag is auto passed as whatever account you're logged into a computer as.

This is wrong. In this case the `--user` flag is specifically for the pip program, you can see this [here](https://pip.pypa.io/en/stable/reference/pip_install/#cmdoption-user).

**Comment by jcklpe** [comment]
@cryzed awesome, thanks for the info!
